server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
      - id: firstroute
        uri: http://localhost:8082
        predicates:
        - Path=/mygateway/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@defaultRateLimiter}"
            key-resolver: "#{@userKeyResolver}"
            default-rate-limit.permitsPerSecond: 5
  application:
    name: my-springboot-gateway
  boot:
    admin:
      client:
        url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /myactuator
  endpoint:
    health:
      show-details: always