server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
      - id: firstroute
        uri: lb://my-springboot-firstApplication
        predicates:
        - Path=/mygateway/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@defaultRateLimiter}"
            key-resolver: "#{@userKeyResolver}"
            default-rate-limit.permitsPerSecond: 5
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: my-springboot-gateway
#  boot:
#    admin:
#      client:
#        url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always